name: Upload Generated Files to Repository

on:
  push:
    branches:
      - master # 监听主分支上的 push 操作

  schedule:
#     - cron: '*/30 * * * *'
    - cron: '0 14 * * *'  # 每天的 22 点执行
    - cron: '0 15 * * *'  # 每天的 23 点执行
    - cron: '30 15 * * *'  # 每天的 23 点 50 分执行
#     - cron: '0 22 * * *'  # 每天的 22 点执行
#     - cron: '0 23 * * *'  # 每天的 23 点执行
#     - cron: '30 23 * * *'  # 每天的 23 点 50 分执行

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

        # 2. 拉取最新的代码
      - name: Pull latest changes from hot
        run: |
          git fetch origin
          git checkout hot
          git pull origin hot

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install  --no-frozen-lockfile

      - name: Build
        run: pnpm run gen

      # 配置 Git 信息
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 添加生成的文件到 Git
      - name: Add and commit files
        run: |
          git add public/*
          git commit -m "Add generated files from GitHub Actions"

      # 推送更改到仓库
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的 GITHUB_TOKEN
        run: |
          git push origin HEAD:hot
